/// <reference lib="webworker" />
// Import OneSignal SDK Worker (Must be first)
importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDKWorker.js');

import { cleanupOutdatedCaches, precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { NavigationRoute, registerRoute } from 'workbox-routing';

declare let self: ServiceWorkerGlobalScope;

// --- 1. Workbox Standard Configuration ---
self.skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by Vite
// __WB_MANIFEST is injected by VitePWA
precacheAndRoute(self.__WB_MANIFEST);

// SPA Navigation Fallback
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
    denylist: [
        /^\/api/,  // Exclude API calls
        /\.[a-z]+$/ // Exclude files with extensions
    ]
});
registerRoute(navigationRoute);


// --- 2. OneSignal & Push Handling ---
// OneSignalSDKWorker.js (imported above) handles the push events automatically.
// We do NOT need to initialize Firebase Messaging here manually anymore.
// This prevents double-handling and token conflicts.

console.log("✅ [SW] Service Worker Initialized (merged with OneSignal)");

// --- 3. Notification Click Handling ---
self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            // If a window is already open, focus it
            for (const client of clientList) {
                if (client.url && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow('/');
            }
        })
    );
});
